http:
  port: 8282

issuer: http://localhost:8282
allowedIssuers:
- http://localhost:8281

---

spring.profiles: docker-compose
  
http:
  port: 80

issuer: http://authorization-ms

allowedIssuers:
- http://authentication-ms
