http:
  port: 8282

issuer: http://localhost:8282

---

spring.profiles: docker-compose
  
http:
  port: 80

issuer: http://authorization-ms

client_validator:
  file: clients-docker.json
  
---

spring.profiles: prod
spring.profiles.include: docker-compose
  