http:
  port: 8282

issuer: http://localhost:8282

client_validator:
  require_origin_check: false

---

spring.profiles: docker-compose
  
http:
  port: 80

issuer: http://authorization-ms

client_validator:
  file: clients-docker.json
  
---

spring.profiles: prod
http:
  port: 80

issuer: http://authorization-ms

client_validator:
  file: clients-prod.json
  