http:
  port: 8282

authorizationEndpoint: http://localhost:8282
allowed_issuers:
- https://trajano.net/sample

---

spring.profiles: docker-compose
  
http:
  port: 80

authorizationEndpoint: http://authorization-ms

spring.hazelcast.config: hazelcast.xml