http:
  port: 8281

authorizationEndpoint: http://localhost:8282
issuer: http://localhost:8281
passwordRequired: password

---

spring.profiles: docker-compose
  
http:
  port: 80

issuer: http://authentication-ms
authorizationEndpoint: http://authorization-ms
