baselines:
- baseline: /v1
  routes:
  - from: /hello
    to: http://localhost:8280/hello
  - from: /s
    to: http://localhost:8280/s
  - from: /authn
    to: http://localhost:8281/
- baseline: /v2
  routes:
  - from: /hello
    to: http://localhost:8280/hello
  - from: /s
    to: http://localhost:8280/s
  - from: /authn
    to: http://localhost:8281/

authorizationEndpoint: http://localhost:8282/
refreshTokenPath: /refresh